### ISSUE TITLE
Änglish

### ISSUE THREAD

**Issue by madflow** [m0ppers/arangodb-arch-docker#1]
- Nouns that refer to people, organisations or places are proper nouns, only proper nouns are capitalised.

So it should be:

`Docker Arangodb Arsch Linux`

Thank you for considering this.

**Comment by m0ppers** [comment]
Thank you for bringing this to my attention! I just changed it. I just noticed that I introduced a typo in the description as well! It should of course be Arch Linux. That is fixed as well. Thank you :uwe: :D

**Comment by madflow** [comment]
:+1: :S

**Comment by jsteemann** [comment]
:dancers:
